var param1 = [];
param1[0]="<font color=\"#FFD300\">Ожидание двигателя</font>";
param1[2]="<font color=\"green\">Работа ПЧ</font>";
param1[4]="<font color=\"#56cea8\">Свободный останов</font>";
param1[6]="<font color=\"#FF0000\">Нет высокого напряжения</font>";
param1[16]="<font color=\"#FF0000\">Авария</font>";
param1[19]="<font color=\"#FFD300\">Переход в тестовый режим</font>";
param1[24]="<font color=\"#FF0000\">Высокая температура в шкафу силовых блоков (55&deg)</font>";
param1[26]="<font color=\"#FF0000\">Предупреждение. Перегрузка двигателя по току</font>";
param1[28]="<font color=\"#FF0000\">Байпас СБ</font>";

var param2 = [];
param2[0]="<font color=\"green\">Нет ошибки</font>";
param2[2]="<font color=\"#FF0000\">Исчезновение главного источника питания</font>";
param2[4]="<font color=\"#FF0000\">Перегрузка двигателя по току</font>";
param2[6]="<font color=\"#FF0000\">Превышение выходного тока ВПЧА</font>";
param2[8]="<font color=\"#FF0000\">Серьезная неисправность силового блока</font>";
param2[10]="<font color=\"#FF0000\">Внешняя неисправность</font>";
param2[12]="<font color=\"#FF0000\">Перегрев трансформатора (150&deg)</font>";
param2[14]="<font color=\"#FF0000\">Перегрев шкафа силовых блоков (60&deg)</font>";
param2[16]="<font color=\"#FF0000\">Выпадение сигнала задания или обратной связи</font>";
param2[18]="<font color=\"#FF0000\">Нет связи с PLC</font>";
param2[20]="<font color=\"#FF0000\">Нет связи с Controller</font>";
param2[21]="<font color=\"#FF0000\">Неизвестная ошибка</font>";
param2[22]="<font color=\"#FF0000\">Неисправность высоковольтного выключателя</font>";
param2[100]="<font color=\"#FF0000\">Ошибка записи значения хотя бы в один регистр</font>";
param2[101]="<font color=\"#FF0000\">Ошибка открытия файла настроек</font>";
param2[102]="<font color=\"#FF0000\">Ошибка сохранения файла настроек</font>";
param2[103]="<font color=\"#FFD300\">Обнаружена ошибка в поле адрес - исправлено</font>";
param2[104]="<font color=\"#FFD300\">Ошибка восстановления паролей</font>";
param2[105]="<font color=\"#FFD300\">Ошибка сохранения паролей</font>";
param2[106]="<font color=\"#FFD300\">Ошибка восстановления файла статистики</font>";
param2[107]="<font color=\"#FFD300\">Ошибка сохранения статистики работы</font>";